laporan.uang-masuk.order-no=N
laporan.uang-masuk.delimiter=;

laporan.penjualan.order-no=M
laporan.penjualan.shipping-name=T
laporan.penjualan.paid-price=AU
laporan.penjualan.tracking-code=BG
laporan.penjualan.delimiter=;

laporan.order.no-pesanan=A
laporan.order.status-pesanan=B
laporan.order.no-resi=E
laporan.order.waktu-pembayaran=K
laporan.order.total-harga-produk=S

laporan.income.no-pesanan=B
laporan.income.total-penghasilan=V

laporan.barang-hilang.no-pesanan=B
laporan.barang-hilang.no-resi=C
laporan.barang-hilang.waktu-pembayaran=D
laporan.barang-hilang.total-harga=E
laporan.barang-hilang.status-pesanan=F

laporan.order-v3.no-pesanan=A
laporan.order-v3.status-pesanan=B
laporan.order-v3.no-resi=AH
laporan.order-v3.waktu-pembayaran=X
laporan.order-v3.total-harga-produk=V
laporan.order-v3.rts-time=Z
laporan.order-v3.last-column=BC

laporan.income-v3.no-pesanan=A
laporan.income-v3.total-penghasilan=AG
laporan.income-v3.sheet-index=3

laporan.barang-hilang-v3.no-pesanan=B
laporan.barang-hilang-v3.no-resi=C
laporan.barang-hilang-v3.waktu-pembayaran=D
laporan.barang-hilang-v3.total-harga=E

laporan.order-v4.no-pesanan=A
laporan.order-v4.status-pesanan=B
laporan.order-v4.no-resi=E
laporan.order-v4.waktu-pembayaran=K
laporan.order-v4.total-harga-produk=S

laporan.income-v4.no-pesanan=C
laporan.income-v4.total-penghasilan=AR
laporan.income-v4.sheet-index=5

laporan.barang-hilang-v4.no-pesanan=B
laporan.barang-hilang-v4.no-resi=C
laporan.barang-hilang-v4.waktu-pembayaran=D
laporan.barang-hilang-v4.total-harga=E
laporan.barang-hilang-v4.status-pesanan=E
