name: stev-report
on:
  push:
    tags:
      - "v*"
    branches:
      - 'main'
      
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up GraalVM Native Image toolchain
        uses: helpermethod/graalvm-native-image-toolchain@0.0.2
        with:
          graalvm-version: 21.2.0
          java-version: 11
      - name: Build
        run: ./mvnw -Pnative package -DskipTests
