name: stev-report
on:
  push:
    tags:
      - "v*"
    branches:
      - 'main'
      
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1.5.0
      - uses: microsoft/setup-msbuild@v1
      - uses: ayltai/setup-graalvm@v1
        with:
          java-version: 11
          graalvm-version: 20.3.0
          native-image: true
      - name: 'Install Native Image Plugin'
        run: |
          gu install native-image
      - name: Build with Maven
        run: mvn -DskipTests -B clean package native-image:native-image --file pom.xml
        shell: powershell
      - name: Run UPX
        uses: crazy-max/ghaction-upx@v1.3.3
        with:
          version: latest
          file: target/stev-report-0.0.1-SNAPSHOT.exe
          args: '-7'
      - uses: actions/upload-artifact@v2
        with:
          if-no-files-found: warn
          name: package
          path: target/*.exe
