name: stev-report
on:
  push:
    tags:
      - "v*"
    branches:
      - 'main'

jobs:
  build-windows-image:
    name: 'Build Windows Image'
    strategy:
      matrix:
        os: ['windows-latest']
        include:
          - os: 'windows-latest'
            label: 'windows'
    runs-on: ${{matrix.os}}

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v1
      
      - name: 'Download GraalVM'
        run: |
          Invoke-RestMethod -Uri https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-21.3.0/graalvm-ce-java11-windows-amd64-21.3.0.zip -OutFile 'graal.zip'
          
      - name: 'Install GraalVM'
        run: |
          Expand-Archive -path 'graal.zip' -destinationpath '.'
          
      - name: 'Install Native Image'
        run: |
          graalvm-ce-java11-21.3.0\bin\gu.cmd install native-image
                    
      - name: 'Set up Visual C Build Tools Workload for Visual Studio 2019 Build Tools'
        run: |
          choco install visualstudio2019-workload-vctools
      
      - name: 'Build Native Image'
        shell: cmd
        env:
          JAVA_HOME: .\graalvm-ce-java11-21.3.0
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Auxiliary\Build\vcvars64.bat" && mvn package -Pnative -DskipTests
          
      - name: 'List Target'
        run: |
          ls target
